framework:
    messenger:
        failure_transport: failed
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - App\Messenger\AuditMiddleware
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - App\Messenger\AuditMiddleware
            query.bus: ~
        
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # We can configure as many transport DSNs as we need and async is just the name of transporter
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    delay: 500
            async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: high
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
        
        routing:
            # Route your messages to the transports
            # We can Route your messages to the multiple transports
            'App\Message\Command\AddPonkaToImage': async_priority_high
            'App\Message\Event\ImagePostDeletedEvent': async
